name: Auto Blog Post

on:
  schedule:
    # Runs at 09:00 UTC on Monday through Friday
    - cron: '0 9 * * 1-5'
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser openai ShopifyAPI

      - name: Run Auto Blog Script
        env:
          SHOP_NAME: ${{ secrets.SHOPIFY_SHOP_NAME }}
          ADMIN_API_ACCESS_TOKEN: ${{ secrets.ADMIN_API_ACCESS_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python auto_blogs.py
